AWSTemplateFormatVersion: 2010-09-09
Description: EC2 template

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-074484c52fc4401e8
      InstanceType: t2.micro
      KeyName: test-for-U
      BlockDeviceMappings:
        - DeviceName: /dev/sdh  
          Ebs:
            VolumeType: io1
            Iops: 200
            DeleteOnTermination: false
            VolumeSize: 20
