name Upload to S3
#--------------------#
# トリガー
#--------------------#
on:
  #-- masterブランチにpushされたら起動する
  push:
    branches:
      - master

#--------------------#
#実際の処理
#--------------------#
jobs:
  build:
    #-- 仮想マシンのOSを指定
    runs-on: ubuntu-latest
    steps:
      #-- Gitリポジトリの内容を取得 --#
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to S3
      #-- Github状に登録した変数を持ってくる
      env:
        AWS_ACCESS_KEY_ID: ${{ sercret.AWS_ACCESS_KEY_ID }}
        AWS_SERCRET_ACCESS_KEY: ${{ sercret.AWS_SECRET_ACCESS_KEY }}
        #-- 仮想マシン用でコマンドを実行 --#
        run:
          aws  s3 sync --delete --region ap-northeast-1 ./files/ s3 ://actiontest/
